## Numpy

Импортировать NumPy под именем np

In [11]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [12]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

Создать вектор размера 10, заполненный единицами

In [13]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

Создать вектор размера 10, заполненный числом 2.5

In [14]:
np.random.choice([2.5], 10)

array([ 2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [15]:
ar = np.zeros(10)
ar[4] = 1
print(ar)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


Развернуть вектор (первый становится последним)

In [16]:
a = np.arange(5)
print(np.flip(a, 0))

[4 3 2 1 0]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [17]:
b = np.arange(9)
print(b.reshape((3,3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [18]:
a = np.nonzero([1, 2, 0, 0, 4, 0])
print(a)

(array([0, 1, 4], dtype=int64),)


Создать 3x3 единичную матрицу

In [19]:
one = np.eye(9)
print(one)

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.]]


Создать массив 3x3x3 со случайными значениями

In [20]:
ren = np.random.random(27).reshape(3,3,3)
print(ren)

[[[ 0.46891822  0.31365073  0.08595532]
  [ 0.07727148  0.17590542  0.13092591]
  [ 0.7106846   0.87176804  0.28470263]]

 [[ 0.89855955  0.10400324  0.65491869]
  [ 0.44496254  0.84366756  0.04712271]
  [ 0.54921996  0.35652562  0.09629009]]

 [[ 0.54500673  0.55480143  0.539271  ]
  [ 0.30497784  0.15971742  0.84973969]
  [ 0.99006454  0.00437088  0.85554322]]]


Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [21]:
b = np.random.random(30)
print(np.mean(b))

0.493466678467


Перемножить матрицы 5x3 и 3x2

In [22]:
a = np.arange(15).reshape(5,3)
b = np.arange(6).reshape(3,2)
print(np.dot(a, b))

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [23]:
a = np.linspace(0.1,0.9,10)
print(a)

[ 0.1         0.18888889  0.27777778  0.36666667  0.45555556  0.54444444
  0.63333333  0.72222222  0.81111111  0.9       ]


Заменить максимальный элемент на ноль

In [24]:
a[a.argmax()] = 0
print(a)

[ 0.1         0.18888889  0.27777778  0.36666667  0.45555556  0.54444444
  0.63333333  0.72222222  0.81111111  0.        ]


Преобразовать массив из float в int

In [25]:
b = np.array([10,5,3,6,4,8,5,3,5], dtype=np.float32)
c = b.astype(dtype=np.int)


Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [26]:
import scipy.spatial

a = np.random.random((10,2))
b = scipy.spatial.distance.cdist(a,a)
print(b)

[[ 0.          0.84948352  1.0667797   0.29189378  0.51142097  0.80670804
   0.70787118  0.47744591  0.68459108  0.80970229]
 [ 0.84948352  0.          0.24281451  0.68112327  0.33822442  0.19882618
   0.45894607  0.55899284  0.30758679  0.20897436]
 [ 1.0667797   0.24281451  0.          0.9200719   0.56355729  0.41399081
   0.68490239  0.70670365  0.54345136  0.42187871]
 [ 0.29189378  0.68112327  0.9200719   0.          0.37002685  0.58314335
   0.4295979   0.53518781  0.4434817   0.58322995]
 [ 0.51142097  0.33822442  0.56355729  0.37002685  0.          0.32702108
   0.38366115  0.33285408  0.25871078  0.33344329]
 [ 0.80670804  0.19882618  0.41399081  0.58314335  0.32702108  0.
   0.27106285  0.63357538  0.14572624  0.01084901]
 [ 0.70787118  0.45894607  0.68490239  0.4295979   0.38366115  0.27106285
   0.          0.71293759  0.16043449  0.26368903]
 [ 0.47744591  0.55899284  0.70670365  0.53518781  0.33285408  0.63357538
   0.71293759  0.          0.59051126  0.64214922]
 [ 0.684

Случайно расположить p элементов в 2D массив

In [27]:
a = np.zeros((5,5))
np.put(a, np.random.choice(range(5*5), 3, replace=False), 1)
print(a)

[[ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.]]


Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [28]:
a = np.array([1,2,3,4,5])
amod = np.zeros(len(a)+(len(a)-1)*3)
amod[::4] = a
print(amod)

[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]


Найти наиболее частое значение в массиве

In [31]:
a = np.random.randint(0,8,40)
print(np.bincount(a).argmax())

1


Найти n наибольших значений в массиве

In [32]:
a = np.random.randint(0,8,40)
b = np.bincount(a)
print('Hаиболее частое значение в массиве: {}, встречается {} раз'.format(b.argmax(), b[b.argmax()]))

Hаиболее частое значение в массиве: 3, встречается 8 раз


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [33]:
import pandas as pd
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
food = pd.read_csv(url, sep='\t')

Посмотреть первые 5 записей

In [34]:
food.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

Сколько наблюдений в наборе данных?


In [35]:
food.shape[0]

4622

Сколько столбцов в наборе данных?

In [36]:
food.shape[1]

5

Напечатайте все названия столбцов

In [37]:
food.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

Какое название у 105 столбца?

In [38]:
food['item_name'][104]
#хоть убейте не понимаю что это за 105ый столбец когда их всего 5

'Veggie Burrito'

Какой тип наблюдений в 105 столбце?

In [39]:
print(food['item_name'].dtype)

object


Как проиндексирован набор данных?

In [40]:
food.index

RangeIndex(start=0, stop=4622, step=1)

Каково значение имени продукта в 19-м наблюдении?

In [41]:
food.item_name[18]

'Canned Soda'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [42]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipo = pd.read_csv(url, sep='\t')
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
order_id              4622 non-null int64
quantity              4622 non-null int64
item_name             4622 non-null object
choice_description    3376 non-null object
item_price            4622 non-null object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB


Как много продуктов стоят более чем $10.00?

In [43]:
a = []
for i in chipo['item_price']:
    b = str(i)
    s = b.replace(b[0],'')
    t = float(s)
    a.append(t)
chipo['item_price'] = a
print(chipo[chipo['item_price'] > 10.].count())
    

order_id              1130
quantity              1130
item_name             1130
choice_description    1123
item_price            1130
dtype: int64


Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [44]:
print(chipo[['item_name', 'item_price']])

                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
5                              Chicken Bowl       10.98
6                             Side of Chips        1.69
7                             Steak Burrito       11.75
8                          Steak Soft Tacos        9.25
9                             Steak Burrito        9.25
10                      Chips and Guacamole        4.45
11                     Chicken Crispy Tacos        8.75
12                       Chicken Soft Tacos        8.75
13                             Chicken Bowl       11.25
14                      Chips and Guacamole        4.45
15    Chips and Tomatillo-Green Chili Salsa        2.39
16                          Chicken Burrito     

Отсортировать по имени предмета

In [45]:
chipo.sort_values(by=['item_name'])

order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
1849       749         1  6 Pack Soft Drink   
1860       754         1  6 Pack Soft Drink   
2713      1076         1  6 Pack Soft Drink   
3422      1373         1  6 Pack Soft Drink   
553        230         1  6 Pack Soft Drink   
1916       774         1  6 Pack Soft Drink   
1922       776         1  6 Pack Soft Drink   
1937       784         1  6 Pack Soft Drink   
3836      1537         1  6 Pack Soft Drink   
298        129         1  6 Pack Soft Drink   
1976       798         1  6 Pack Soft Drink   
1167       481         1  6 Pack Soft Drink   
3875      1554         1  6 Pack Soft Drink   
1124       465         1  6 Pack Soft Drink   
3886      1558         1  6 Pack Soft Drink   
2108       849         1  6 Pack Soft Drink   
3010      1196         1  6 Pack Soft Drink   
4535      1803         1  6 Pack Soft Drink   
4169      1664         1  6 Pack Soft Drink   
4174      1666         1  6 Pack Soft Drink   
4527      1800         1  6 Pack Soft Drink   
4522      1798         1  6 Pack Soft Drink   
3806      1525         1  6 Pack Soft Drink   
2389       949         1  6 Pack Soft Drink   
3132      1248         1  6 Pack Soft Drink   
3141      1253         1  6 Pack Soft Drink   
639        264         1  6 Pack Soft Drink   
1026       422         1  6 Pack Soft Drink   
...        ...       ...                ...   
2996      1192         1       Veggie Salad   
3163      1263         1       Veggie Salad   
4084      1635         1       Veggie Salad   
1694       686         1       Veggie Salad   
2756      1094         1       Veggie Salad   
4201      1677         1  Veggie Salad Bowl   
1884       760         1  Veggie Salad Bowl   
455        195         1  Veggie Salad Bowl   
3223      1289         1  Veggie Salad Bowl   
2223       896         1  Veggie Salad Bowl   
2269       913         1  Veggie Salad Bowl   
4541      1805         1  Veggie Salad Bowl   
3293      1321         1  Veggie Salad Bowl   
186         83         1  Veggie Salad Bowl   
960        394         1  Veggie Salad Bowl   
1316       536         1  Veggie Salad Bowl   
2156       869         1  Veggie Salad Bowl   
4261      1700         1  Veggie Salad Bowl   
295        128         1  Veggie Salad Bowl   
4573      1818         1  Veggie Salad Bowl   
2683      1066         1  Veggie Salad Bowl   
496        207         1  Veggie Salad Bowl   
4109      1646         1  Veggie Salad Bowl   
738        304         1  Veggie Soft Tacos   
3889      1559         2  Veggie Soft Tacos   
2384       948         1  Veggie Soft Tacos   
781        322         1  Veggie Soft Tacos   
2851      1132         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   
1395       567         1  Veggie Soft Tacos   

                                     choice_description  item_price  
3389                                        [Diet Coke]       12.98  
341                                         [Diet Coke]        6.49  
1849                                             [Coke]        6.49  
1860                                        [Diet Coke]        6.49  
2713                                             [Coke]        6.49  
3422                                             [Coke]        6.49  
553                                         [Diet Coke]        6.49  
1916                                        [Diet Coke]        6.49  
1922                                             [Coke]        6.49  
1937                                        [Diet Coke]        6.49  
3836                                             [Coke]        6.49  
298                                            [Sprite]        6.49  
1976                                        [Diet Coke]        6.49  
1167                                             [Coke]        6.49  
3875                                     

Сколько было заказано самого дорогого предмета?

In [46]:
chipo.sort_values(by=['item_price'])
chipo[chipo['item_name']==chipo['item_name'][0]].count()                  

order_id              110
quantity              110
item_name             110
choice_description      0
item_price            110
dtype: int64

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [47]:
chipo[chipo['item_name']=='Veggie Salad Bowl'].count()   

order_id              18
quantity              18
item_name             18
choice_description    18
item_price            18
dtype: int64

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [48]:
a = chipo[chipo['item_name']=='Canned Soda']
b = chipo['order_id'].value_counts()
c = 0

for i in a['order_id']:
    if  b[i] > 1:
        c = c + 1

print(c)

104
